Repository SkywardAI/skywardai.io, pull requests merged in 2024-06, with the labels that each got.

#13 added projectinfo.md with documentation on project
  assets/images/ticket_list.png
  assets/images/tickets.png
  assets/images/ui_chat.png
  assets/images/ui_ticketlist.png
  docs/development/build_and_run.md
  docs/projectinfo.md
  docs/quick-start.md
Labels: documentation, enhancement

#16 Add projectinfo page into docs folder
  docs/tutorial/projectinfo.md
Labels: bug, documentation

#17 add new way to deployment
  docs/development/build_and_run.md
Labels: documentation
